#' Make tabular summary of a pipeline
#'
#' @family from_Rmonad
#' @param m An Rmonad
#' @param code logical Should the code by included?
#' @export
mtabulate <- function(m, code=FALSE){
  data.frame(
    code        = ms_code(m) %>% sapply(paste0, collapse="\n"),
    id          = ms_id(m) %>% as.numeric,
    OK          = ms_OK(m),
    cached      = has_value(m),
    time        = ms_time(m) %>% sapply(function(x) { signif(.[1], 2) }),
    space       = ms_mem(m),
    is_nested   = ms_nest(m)       %>% sapply(length),
    ndependents = ms_dependents(m) %>% sapply(length),
    nnotes      = ms_notes(m)      %>% sapply(length),
    nwarnings   = ms_warnings(m)   %>% sapply(length),
    error       = ms_error(m)      %>% sapply(length),
    doc         = ms_doc(m)        %>% sapply(length)
  ) %>% {
    if(!code)
      .$code <- NULL
    .
  }
}

#' Tabulates all errors, warnings and notes
#' 
#' @family from_Rmonad
#' @param m An Rmonad
#' @export
missues <- function(m){

  error_len   <- ms_error(m)    %>% sapply(length)
  warning_len <- ms_warnings(m) %>% sapply(length)
  note_len    <- ms_notes(m)    %>% sapply(length)

  ids <- ms_id(m) %>% {c(
    rep(., times=error_len),
    rep(., times=warning_len),
    rep(., times=note_len)
  )}

  error    <- ms_error(m)    %>% unlist %>% as.character
  warnings <- ms_warnings(m) %>% unlist %>% as.character
  notes    <- ms_notes(m)    %>% unlist %>% as.character
  data.frame(
    id = ids,
    type = c(
      rep("error",   length(error)),
      rep("warning", length(warnings)),
      rep("note",    length(notes))
    ),
    issue = c(error, warnings, notes)
  )
}

#' Returns the value of a monad holds
#'
#' If the monad is in the passing state, return the wrapped value. Otherwise,
#' raise an appropriate error.
#'
#' Regardless of pass/fail status, \code{esc} raises all collected warnings and
#' prints all messages. Terminating a monadic sequence with \code{esc} should
#' obtain a result very close to running the same code outside the monad. The
#' main difference is that Rmonad appends the toplevel code that generated the
#' error.
#'
#' @family from_Rmonad
#' @param m An Rmonad
#' @param quiet If TRUE, print the exact messages that are raised, without
#'        extra context. 
#' @export 
esc <- function(m, quiet=FALSE){

  .quiet_warning <- function(code, msg) warning(msg, call.=FALSE)
  .quiet_note    <- function(code, msg) message(msg)
  .quiet_error   <- function(code, msg) stop(msg, call.=FALSE)
  .unquiet_warning <- function(code, msg) {
    warning("in '", code, "': ", msg, call.=FALSE)
  }
  .unquiet_note <- function(code, msg) {
    message(msg)
  }
  .unquiet_error <- function(code, msg) {
    stop(paste0('in "', code, '":\n  ', msg), call.=FALSE)
  }

  mtab <- mtabulate(m, code=TRUE)

  issues <- missues(m) %>%
    { merge(mtab, .)[, c("code", "type", "issue")] }

  if(quiet){
    fw <- .quiet_warning
    fn <- .quiet_note
    fe <- .quiet_error
  } else {
    fw <- .unquiet_warning
    fn <- .unquiet_note
    fe <- .unquiet_error
  }

  for(i in seq_len(nrow(issues))){
    # raise warnings, with contextual information
    if(issues[i, "type"] == "warning"){
      fw(issues[i, "code"], issues[i, "issue"])
    }
    # pass messages verbatim
    if(issues[i, "type"] == "note"){
      fn(issues[i, "code"], issues[i, "issue"])
    }
  }
  if(! m_OK(m)){
    fe(m_code(m), m_error(m))
  }

  m_value(m)
}

#' Convert a pipeline to Rmarkdown
#'
#' Plots an rmonad workflow, summarizes the nodes, lists isses, and lists
#' details for each node. This function is likely to change extensively in the
#' future. It should be seen as one example of the kind of report that can be
#' generated by rmonad, rather than THE report.
#'
#' @family from_Rmonad
#' @param m An Rmonad
#' @param prefix A file prefix for the generated report
#' @export
#' @examples
#' \dontrun{
#' mreport(-1:2 %>>% log %>>% sqrt %__% "asdf" %>>% sqrt)
#' }
mreport <- function(
  m,
  prefix='report'
){

  dir <- tempdir()
  m_path <- file.path(dir, 'rmonad.Rd')
  r_path <- file.path(dir, 'report.Rmd')
  md_path <- file.path(dir, paste0(prefix, ".md"))

  saveRDS(m, m_path) 

  tostr <- function(x, prefix){
    if(.is_not_empty_string(x)){
      paste0(prefix, x, "\n", collapse="\n")
    } else {
      ""
    }
  }

  strsummary <- function(m, i){
    if(is.null(m_summary(m, i))){
      ""
    } else {
      sprintf("```{r, echo=FALSE}\nm_summary(m, %s)\n```", i)
    }
  }

  entries <- ms_id(m) %>% sapply( function(i)
    glue::glue(.open='{{', .close='}}',
      "
      ## {{id}}

      OK={{ok}} | parents={{parents}} | cached={{cached}} | time={{time}} | memory={{mem}}

      {{doc}}

      ```{r, eval=FALSE}
      {{code}}
      ```

      {{error}}
      {{warnings}}
      {{notes}}
      {{summary}}
      ",
      id       = i,
      ok       = m_OK(m, i),
      parents  = paste0("[", paste(m_parents(m, i), collapse=", "), "]"),
      cached   = has_value(m, index=i),
      time     = m_time(m, i),
      mem      = m_mem(m, i),
      doc      = tostr(m_doc(m, i)),
      code     = paste0(m_code(m, i), collapse="\n"),
      error    = tostr(m_error(m, i), "ERROR: "),
      warnings = tostr(m_warnings(m, i), "WARNING: "),
      notes    = tostr(m_notes(m, i), "NOTE: "),
      summary  = strsummary(m, i)
    )) %>% paste0(collapse="\n")

  rmd_str <- glue::glue(.open='{{', .close='}}',
    "
    ```{r, echo=FALSE}
    m <- readRDS('rmonad.Rd')
    ```

    ```{r, echo=FALSE}
    library(rmonad)
    library(knitr)
    ```

    ```{r, echo=FALSE}
    plot(m)
    ```

    ```{r, results='asis', echo=FALSE}
    kable(mtabulate(m))
    ```

    ```{r, results='asis', echo=FALSE}
    kable(missues(m))
    ```

    ```{r, echo=FALSE}
    print(m)
    ```

    {{entries}}
    ",
    entries=entries
  )

  write(rmd_str, file=r_path)

  knitr::knit(input=r_path, output=md_path)
  out_path <- knitr::pandoc(input=md_path, format='latex', ext='pdf')
  file.copy(out_path, getwd(), overwrite=TRUE)
}
