#' Make tabular summary of a pipeline
#'
#' @family from_Rmonad
#' @param m An Rmonad
#' @param code logical Should the code by included?
#' @export
mtabulate <- function(m, code=FALSE){
  data.frame(
    code      = igraph::V(m@graph)$code %>% paste(collapse="\n"),
    id        = igraph::V(m@graph) %>% as.numeric,
    OK        = igraph::V(m@graph)$OK,
    cached    = igraph::V(m@graph)$value %>% sapply(function(x) x@chk()),
    time      = igraph::V(m@graph)$time %>% { signif(.[1], 2) },
    space     = igraph::V(m@graph)$mem,
    # is_nested = has_nest(m),
    # nbranch   = length(m_branch(m)),
    nnotes    = igraph::V(m@graph)$notes    %>% sapply(length),
    nwarnings = igraph::V(m@graph)$warnings %>% sapply(length),
    error     = igraph::V(m@graph)$error    %>% sapply(length),
    doc       = igraph::V(m@graph)$doc      %>% sapply(length)
  ) %>% {
    if(!code)
      .$code <- NULL
    .
  }
}

#' Tabulates all errors, warnings and notes
#' 
#' @family from_Rmonad
#' @param m An Rmonad
#' @param recurse_nests logical Should the resulting table descend into nested pipelines?
#' @export
missues <- function(m, recurse_nests=TRUE){
  ids      <- igraph::V(m@graph) %>% as.numeric
  error    <- igraph::V(m@graph)$error    %>% unlist
  warnings <- igraph::V(m@graph)$warnings %>% unlist
  notes    <- igraph::V(m@graph)$notes    %>% unlist
  data.frame(
    id = ids, 
    type = c(
      rep("error", length(error)),
      rep("warning", length(warnings)),
      rep("note", length(notes))
    ),
    issue = c(error, warnings, notes)
  )
}

#' Convert a pipeline to Rmarkdown
#'
#' STUB
#'
#' @family from_Rmonad
#' @param m An Rmonad
#' @export
mreport <- function(m){
  stop("NOT IMPLEMENTED")
}

#' Returns the value of a monad holds
#'
#' If the monad is in the passing state, return the wrapped value. Otherwise,
#' raise an appropriate error.
#'
#' Regardless of pass/fail status, \code{esc} raises all collected warnings and
#' prints all messages. Terminating a monadic sequence with \code{esc} should
#' obtain a result very close to running the same code outside the monad. The
#' main difference is that Rmonad appends the toplevel code that generated the
#' error.
#'
#' @family from_Rmonad
#' @param m An Rmonad
#' @param quiet If TRUE, print the exact messages that are raised, without
#'        extra context. 
#' @export 
esc <- function(m, quiet=FALSE){
  mtab <- mtabulate(m, recurse_nests=TRUE, code=TRUE)

  issues <- missues(m, recurse_nests=TRUE) %>%
    { merge(mtab, .)[, c("code", "type", "issue")] }

  if(quiet){
    fw <- .quiet_warning
    fn <- .quiet_note
    fe <- .quiet_error
  } else {
    fw <- .unquiet_warning
    fn <- .unquiet_note
    fe <- .unquiet_error
  }

  for(i in seq_len(nrow(issues))){
    # raise warnings, with contextual information
    if(issues[i, "type"] == "warning"){
      fw(issues[i, "code"], issues[i, "issue"])
    }
    # pass messages verbatim
    if(issues[i, "type"] == "note"){
      fn(issues[i, "code"], issues[i, "issue"])
    }
  }
  if(! m_OK(m)){
    fe(m_code(m), m_error(m))
  }

  m_value(m)
}

.quiet_warning <- function(code, msg) warning(msg, call.=FALSE)
.quiet_note    <- function(code, msg) message(msg)
.quiet_error   <- function(code, msg) stop(msg, call.=FALSE)

.unquiet_warning <- function(code, msg) {
  warning("in '", code, "': ", msg, call.=FALSE)
}
.unquiet_note <- function(code, msg) {
  message(msg)
}
.unquiet_error <- function(code, msg) {
  stop(paste0('in "', code, '":\n  ', msg), call.=FALSE)
}


#' Return each independent branch of the pipeline
#'
#' Branches are generated by the \code{\%>^\%} operator. The allow a value to
#' be sent into a new branch of the pipeline, which can fail independently,
#' without propagating to other pieces of the program.
#'
#' @param m An Rmonad
#' @return A list of Rmonads, one for each branch
#' @export
unbranch <- function(m){

  as.list(m)               %>%
    Filter(f=has_branch)   %>%
    lapply(m_branch)       %>%
    lapply(rev)            %>%
    unlist                 %>%
    append(x=list(m))

}
